name: Merge tests

on:
  merge_group:

jobs:
  merge-queue-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: Sleep for 1 minutes
      run: sleep 60
